name: vol_spotter_platform_interface
description: >-
  A common platform interface for the vol_spotter plugin. Provides the abstract
  classes, models, and method channel implementation used by platform packages.
version: 0.1.0+2
repository: https://github.com/Crdzbird/vol_spotter

environment:
  sdk: ^3.11.0
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
