name: vol_spotter_windows
description: >-
  Windows stub implementation of the vol_spotter plugin. Physical button
  detection is not supported on Windows.
version: 0.1.0+1
repository: https://github.com/Crdzbird/vol_spotter

environment:
  sdk: ^3.11.0
  flutter: '>=3.27.0'

flutter:
  plugin:
    implements: vol_spotter
    platforms:
      windows:
        pluginClass: VolSpotterWindows
        dartPluginClass: VolSpotterWindows

dependencies:
  flutter:
    sdk: flutter
  vol_spotter_platform_interface: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
