name: vol_spotter
description: >-
  A Flutter plugin for detecting physical button presses (volume up, volume
  down, power) on Android and iOS with configurable event interception.
version: 0.2.1
repository: https://github.com/Crdzbird/vol_spotter

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: vol_spotter_android
      ios:
        default_package: vol_spotter_ios
      linux:
        default_package: vol_spotter_linux
      macos:
        default_package: vol_spotter_macos
      web:
        default_package: vol_spotter_web
      windows:
        default_package: vol_spotter_windows

dependencies:
  flutter:
    sdk: flutter
  vol_spotter_android: ^0.2.1
  vol_spotter_ios: ^0.2.1
  vol_spotter_linux: ^0.2.1
  vol_spotter_macos: ^0.2.1
  vol_spotter_platform_interface: ^0.2.1
  vol_spotter_web: ^0.2.1
  vol_spotter_windows: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.2.0
