name: vol_spotter_web
description: >-
  Web stub implementation of the vol_spotter plugin. Physical button
  detection is not supported on the web.
version: 0.1.0+1
repository: https://github.com/Crdzbird/vol_spotter

environment:
  sdk: ^3.11.0
  flutter: '>=3.27.0'

flutter:
  plugin:
    implements: vol_spotter
    platforms:
      web:
        pluginClass: VolSpotterWeb
        fileName: vol_spotter_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  vol_spotter_platform_interface: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
